### ISSUE TITLE
R?

### ISSUE THREAD

**Issue by ConceptDelta** [anvaka/pm#1]
It's hard to tell what software is being searched. If it's not included, could you add in R? 

https://en.wikipedia.org/wiki/R_(programming_language)

**Comment by anvaka** [comment]
Sure! What would be the best place to get list of R packages and their dependencies? Is it [CRAN](https://cran.r-project.org/) or something else?

**Comment by ConceptDelta** [comment]
Awesome. 

Yeah, CRAN is probably your best bet, though GitHub has a bunch as well. I attached a paper I'm working on with my student that examines the ggplot2 R package.

If you're interested, I'd be happy to help you turn the R visualization into a journal publication.

Cheers,
Roger






> On Jul 22, 2015, at 11:34 PM, Andrei Kashcha <notifications@github.com> wrote:
> 
> Sure! What would be the best place to get list of R packages and their dependencies? Is it CRAN <https://cran.r-project.org/> or something else?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/anvaka/pm/issues/1#issuecomment-123952866>.
> 


------------------------------------------------------
Roger S. Taylor, Ph.D.
Assistant Professor
Department of Psychology 
Human Computer Interaction (HCI) program
State University of New York at Oswego

Office: 464 Mahar Hall
Phone: (315) 312-4150
Email: roger.taylor@oswego.edu

**Comment by erasche** [comment]
MRAN is also a good place to grab dependencies from, since they have them already parsed.
https://mran.revolutionanalytics.com/packages/info/?A3#depend

**Comment by anvaka** [comment]
Thanks for the link to mran! I'll create indexer, hopefully this weekend, and we'll see how it looks like :).

**Comment by anvaka** [comment]
[This is R](http://anvaka.github.io/pm/#/galaxy/cran?cx=-2482&cy=-5685&cz=-291&lx=0.2264&ly=-0.6790&lz=0.4330&lw=0.5480&ml=200&s=2.75&l=1&v=2015-07-24T23-30-00Z).

**Comment by ConceptDelta** [comment]
Nice! Is there a way to highlight the connections? 

For instance, if I select ggplot2 (for example) it list 180 dependencies. However, I can't see the links to the other nodes - it gets buried in the noise.


> On Jul 25, 2015, at 5:34 PM, Andrei Kashcha <notifications@github.com> wrote:
> 
> Closed #1 <https://github.com/anvaka/pm/issues/1>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/anvaka/pm/issues/1#event-365311003>.
> 



------------------------------------------------------
Roger S. Taylor, Ph.D.
Assistant Professor
Department of Psychology 
Human Computer Interaction (HCI) program
State University of New York at Oswego

Office: 464 Mahar Hall
Phone: (315) 312-4150
Email: roger.taylor@oswego.edu

**Comment by erasche** [comment]
@ConceptDelta maybe something like I proposed in #3?

**Comment by ConceptDelta** [comment]
Exactly.
