### ISSUE TITLE
Node details window overlaps degrees result window

### ISSUE THREAD

**Issue by Gyscos** [anvaka/pm#10]
When a node label is too long to fit on a single line, the node details window gets taller and hides the degrees result window behind it.

**Comment by anvaka** [comment]
Thanks for reporting this!

I was able to reproduce this with 50 character long package:

![image](https://cloud.githubusercontent.com/assets/225407/10184265/2189b9ea-66ef-11e5-9c57-fc3ec5b6259b.png)

**Comment by anvaka** [comment]
Should be fixed now
